### ISSUE TITLE
Split one or multiple sprite sheets from a folder

### ISSUE THREAD

**Issue by Gui0delp** [dilaouid/santoryu.py#1]
Why not add an arguments or a test for give the possibility to split one or more sprites sheets into a directory ?
It can be a good feature ?

`py ./santoryu.py [dirname] [parameters]`

**Comment by dilaouid** [comment]
Nice idea! I'm on it

> Why not add an arguments or a test for give the possibility to split one or more sprites sheets into a directory ? It can be a good feature ?
> 
> `py ./santoryu.py [dirname] [parameters]`

**Comment by dilaouid** [comment]
Done, now you can also insert directories names in the arguments list
